"use strict";

exports.__esModule = true;
exports.default = void 0;
var DOLLAR = '$,.2f';
var DOLLAR_SIGNED = '+$,.2f';
var DOLLAR_ROUND = '$,d';
var DOLLAR_ROUND_SIGNED = '+$,d';
var FLOAT_1_POINT = ',.1f';
var FLOAT_2_POINT = ',.2f';
var FLOAT_3_POINT = ',.3f';
var FLOAT = FLOAT_2_POINT;
var FLOAT_SIGNED_1_POINT = '+,.1f';
var FLOAT_SIGNED_2_POINT = '+,.2f';
var FLOAT_SIGNED_3_POINT = '+,.3f';
var FLOAT_SIGNED = FLOAT_SIGNED_2_POINT;
var INTEGER = ',d';
var INTEGER_SIGNED = '+,d';
var PERCENT_1_POINT = ',.1%';
var PERCENT_2_POINT = ',.2%';
var PERCENT_3_POINT = ',.3%';
var PERCENT = PERCENT_2_POINT;
var PERCENT_SIGNED_1_POINT = '+,.1%';
var PERCENT_SIGNED_2_POINT = '+,.2%';
var PERCENT_SIGNED_3_POINT = '+,.3%';
var PERCENT_SIGNED = PERCENT_SIGNED_2_POINT;
var SI_1_DIGIT = '.1s';
var SI_2_DIGIT = '.2s';
var SI_3_DIGIT = '.3s';
var SI = SI_3_DIGIT;
var SMART_NUMBER = 'SMART_NUMBER';
var SMART_NUMBER_SIGNED = 'SMART_NUMBER_SIGNED';
var NumberFormats = {
  DOLLAR: DOLLAR,
  DOLLAR_ROUND: DOLLAR_ROUND,
  DOLLAR_ROUND_SIGNED: DOLLAR_ROUND_SIGNED,
  DOLLAR_SIGNED: DOLLAR_SIGNED,
  FLOAT: FLOAT,
  FLOAT_1_POINT: FLOAT_1_POINT,
  FLOAT_2_POINT: FLOAT_2_POINT,
  FLOAT_3_POINT: FLOAT_3_POINT,
  FLOAT_SIGNED: FLOAT_SIGNED,
  FLOAT_SIGNED_1_POINT: FLOAT_SIGNED_1_POINT,
  FLOAT_SIGNED_2_POINT: FLOAT_SIGNED_2_POINT,
  FLOAT_SIGNED_3_POINT: FLOAT_SIGNED_3_POINT,
  INTEGER: INTEGER,
  INTEGER_SIGNED: INTEGER_SIGNED,
  PERCENT: PERCENT,
  PERCENT_1_POINT: PERCENT_1_POINT,
  PERCENT_2_POINT: PERCENT_2_POINT,
  PERCENT_3_POINT: PERCENT_3_POINT,
  PERCENT_SIGNED: PERCENT_SIGNED,
  PERCENT_SIGNED_1_POINT: PERCENT_SIGNED_1_POINT,
  PERCENT_SIGNED_2_POINT: PERCENT_SIGNED_2_POINT,
  PERCENT_SIGNED_3_POINT: PERCENT_SIGNED_3_POINT,
  SI: SI,
  SI_1_DIGIT: SI_1_DIGIT,
  SI_2_DIGIT: SI_2_DIGIT,
  SI_3_DIGIT: SI_3_DIGIT,
  SMART_NUMBER: SMART_NUMBER,
  SMART_NUMBER_SIGNED: SMART_NUMBER_SIGNED
};
var _default = NumberFormats;
exports.default = _default;